In [9]:
# NLP Example
import torch
import torch.nn as nn
batch, sentence_length, embedding_dim = 1, 5,3
embedding = torch.randn(batch, sentence_length, embedding_dim)
print(embedding)
layer_norm = nn.LayerNorm(embedding_dim)
# Activate module
# calculate mean and variance
# normalize
print(embedding.mean(1, keepdim=True))
print(embedding.var(1, keepdim=True, unbiased=False))
print(embedding.std(1, keepdim=True, unbiased=False))
nor_embedding = (embedding - embedding.mean(1, keepdim=True)) / embedding.std(1, keepdim=True, unbiased=False)
print(nor_embedding)
print(layer_norm(embedding))


tensor([[[-0.1581,  1.0007,  0.5797],
         [ 0.2948,  1.2885, -0.4634],
         [-0.3178,  0.4968, -0.1996],
         [ 1.8562,  1.1509, -0.9048],
         [ 0.7747, -0.5693,  0.9551]]])
tensor([[[ 0.4900,  0.6735, -0.0066]]])
tensor([[[0.6116, 0.4578, 0.4642]]])
tensor([[[0.7821, 0.6766, 0.6814]]])
tensor([[[-1.3200,  1.0995,  0.2205],
         [-0.1094,  1.2758, -1.1664],
         [-0.8651,  1.4013, -0.5362],
         [ 0.9865,  0.3843, -1.3708],
         [ 0.5704, -1.4059,  0.8355]]], grad_fn=<NativeLayerNormBackward>)
